[[language]]
name = "json"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.json"
] }
auto-format = true

[[language]]
name = "jsonc"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.jsonc"
] }
auto-format = true

[[language]]
auto-format = true
name = "c-sharp"
formatter = { command = "csharpier" }
language-servers = ["csharp-ls"]

[[language]]
auto-format = true
name = "rust"
language-servers = [
  "rust-analyzer",
  # "helix-assist"
]

[[language]]
auto-format = true
name = "toml"
formatter = { command = "tombi", args = ["fmt", "-"] }
language-servers = [
  "tombi",
]

[language-server.csharp-ls]
command = "csharp-ls"

# [language-server.helix-assist]
# command = "helix-assist"
# # Optional
# args = ["--handler", "anthropic", "--num-suggestions", "1"]
