theme ="onedark"

[editor]
line-number = "relative"
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)

[keys.insert]
j = { k = "normal_mode" }
C-s = ["normal_mode",":w"]

[editor.file-picker]
hidden = false